### ISSUE TITLE
CI or process required to keep CDN up to date

### ISSUE THREAD

**Issue by m-gagne** [EvanBoyle/AzSearch.js#12]
Currently the CDN hosted version of AzSearch is at 0.0.13, what is the process to update it with the latest builds?

`https://cdn.jsdelivr.net/azsearch.js/0.0.13/AzSearch.bundle.js`

**Comment by EvanBoyle** [comment]
I'm going to be looking into some better process for releasing with travisCI integration next week. I do have CDN mirroring setup against NPM, so all that needs to be done is an appropriate version update, I need to do more reading on [semver](http://semver.org) and make sure we're following a reasonable versioning strategy. After updating the version we just publish the updated package to NPM, and the CDN should pick up the new version within 30 minutes.

**Comment by EvanBoyle** [comment]
We should discuss how we want to do this though. Cutting a new version with every build/check-in is probably a little too much. What about releasing an update once a week unless we have a demo, breaking bug, or some other forcing function?

**Comment by EvanBoyle** [comment]
Closing for now, we have auto CDN mirroring that gets triggered when a new npm version is published.

**Comment by EvanBoyle** [comment]
According to semver, anthing pre 1.0 doesn't have to follow normal versioning as it is in active development/prerelease
