### ISSUE TITLE
Enhance result template

### ISSUE THREAD

**Issue by m-gagne** [EvanBoyle/AzSearch.js#19]
With pricing being added the results can now be taller than the thumbnail. Suggest we reformat the data so it's a consistent height.

**Comment by m-gagne** [comment]
An idea of how to update the result listing, would need to optimize for mobile as well.
![result-update](https://cloud.githubusercontent.com/assets/741732/25492387/e36f58dc-2b40-11e7-83db-4823b1a46a55.PNG)

**Comment by EvanBoyle** [comment]
Look's great, I really like the icons. Can probably just force the icons to stack for mobile.

**Comment by m-gagne** [comment]
![icon-resize](https://cloud.githubusercontent.com/assets/741732/25498665/e8aaef8a-2b56-11e7-8121-c24b1712212f.gif)

I found I was having to introduce "realestate" specific style into azsearch.css, so for this I created a separate css file (realestate.css) and migrated the realestate.local.html file into a samples folder so now there is

```
/samples
/samples/realestate.local.html
/samples/css/realestate.css
```

Not sure if we want a samples folder, but if we do we could move realestate & channel9 into it completely.

**Comment by EvanBoyle** [comment]
can you do an inline stylesheet in the file? I think it's a real benefit that the app is a single file, especially for the generator.

**Comment by m-gagne** [comment]
moved back inline and kept it in the root folder =)
