### ISSUE TITLE
Flag/Option for API vs direct search

### ISSUE THREAD

**Issue by m-gagne** [EvanBoyle/AzSearch.js#28]
We should include an ability to call an intermediary API that would hide the query key from the clients should desire such behavior. This would include refactoring to make QueryKey & Service optional, and introduce a flag to enable API mode as well as API endpoint.

Question being should we pass the search parameters via query string as we do when directly calling search or (perhaps optionally) POST as JSON object.

**Comment by EvanBoyle** [comment]
This feature already exists. You can set a search or suggest callback that will be used in place of calling the api directly. See [docs](https://github.com/EvanBoyle/AzSearchStore#calling-your-own-server) for more.

**Comment by m-gagne** [comment]
Doh! How did I missed this! (did not RTFM)
