### ISSUE TITLE
FAILED to parse index and create file

### ISSUE THREAD

**Issue by ttianr** [EvanBoyle/AzSearch.js#48]
When running the generate i'm getting the error "FAILED to parse index and create file" but unable to diagnose where the issue could be

**Comment by zachrenwick** [comment]
@ttianr  This is also happening to me.. how did you fix it?

**Comment by ttianr** [comment]
I seem to remember it was the JSON file not going in correctly but I cannot 100% remember. It definitely was user error though and did work correctly in the end.

**Comment by HyemiSong** [comment]
@ttianr @zachrenwick  I have a same issue.
