### ISSUE TITLE
Feature: sorting control

### ISSUE THREAD

**Issue by EvanBoyle** [EvanBoyle/AzSearch.js#5]
Would be great to have a drop down control that allows sorting by fields specified by the user. A few examples:

- orderby=lastRenovationDate desc
- $orderby=geo.distance(location, geography'POINT(-122.12315 47.88121)')

There is already the ability to set the orderby clause from azsearchstore search parameters, but it may also be worth adding a higher level api that builds sorting string, especially for geo sorting.

**Comment by m-gagne** [comment]
What do you think of the position of the control here? The other thought is to have it in the same section as the search results themselves (on the right).
![sorty](https://cloud.githubusercontent.com/assets/741732/25364798/e9c6d24c-2932-11e7-8aa7-9c75a6148805.PNG)

**Comment by m-gagne** [comment]
Here's what I've got so far. Very basic, only supports simple orderBy <field> desc, still need to add geo support. 

Changes can be seen [here](https://github.com/EvanBoyle/AzSearch.js/compare/master...m-gagne:issue-5). Will create PR once I sort out geo.

**Demo:**
![untitled](https://cloud.githubusercontent.com/assets/741732/25366857/6a9b5bc4-2940-11e7-960a-eec1575f50a9.gif)

**Comment by EvanBoyle** [comment]
This looks great! I think the sidebar seems like a good spot, others can always customize the template if they want. Looked at the code and it looks good so far! Do you think it would be possible to have a default option that's always included for sorting by "relevance"? This would basically allow the user to get back to the default behavior which is results ordered by @search.score (no $orderby clause specified).

**Comment by m-gagne** [comment]
Would is make sense to default to "Relevance" (score, aka no implicit orderBy clause) as a default? which can be user overwritten? See `defaultSortFieldName` in API below?

`public addSortBy(htmlId: string, fields: [{title: string, field: string}], defaultSortFieldName?: string, cssClasses?: { [key: string]: string; })`

**Comment by EvanBoyle** [comment]
Yeah that sounds great!

**Comment by m-gagne** [comment]
I'm going to create a separate issue for geo enhancement in the result set and filtering as it's a larger task.

**Comment by m-gagne** [comment]
Resolves with PR #13
